### PR TITLE
Fix/issue 55/lsn tokens

### LINKED ISSUE #55: use lsn as continuation tokens where possible
Currently, datasets using CDC enabled tables can create continuation tokens using timestamps. 

In cases where the creation of such a timestamp token coincides with the delay time frame between changes being committed to the source table, and them appearing in the CDC table, changes may be invisible for the next incremental request using the aforementioned timestamp token.

Using mssql log sequence numbers (__start_lsn, __seq_lsn) as continuation tokens should make the delay irrelevant, resulting in a robuster mechanism. 

Also, care must be taken to cover cases where a token/lsn is older than the oldest lsn in the retention span of CDC.

### PR DESCRIPTION
**Pull request by rompetroll**
closes #55 

this change uses LSN numbers from the cdc logs as continuation tokens.

### CODE REVIEW

File: internal/db/query.go [hunk 1]
```diff
@@ -95,21 +96,28 @@ type CDCQuery struct {
...
-		SELECT @begin_lsn = sys.fn_cdc_map_time_to_lsn('smallest greater than', @begin_time);
-		SELECT @end_lsn = sys.fn_cdc_map_time_to_lsn('largest less than or equal', @end_time);
-		SELECT t.* FROM [cdc].[dbo_%s_CT] AS t WHERE (t.__$start_lsn <= @end_lsn) AND (t.__$start_lsn >= @begin_lsn);
-		`, date, q.TableDef.TableName)
+	lastLsn := fmt.Sprintf("sys.fn_cdc_get_min_lsn('%s_%s')", schema, q.TableDef.TableName)
+	data, err := base64.RawURLEncoding.DecodeString(q.Request.Since)
+	if err == nil && strings.HasPrefix(string(data), "0x") && len(data) == 22 {
+		lastLsn = fmt.Sprintf("CONVERT(binary(10), %s)", string(data))
+	}
+	//query := fmt.Sprintf(`
```
Comment (gra-moore) [inline internal/db/query.go:109]: remove the debugging and commented out lines from the PR

File: internal/db/query.go [hunk 2]
```diff
@@ -95,21 +96,28 @@ type CDCQuery struct {
...
+	//	`, schema, q.TableDef.TableName, string(data))
 
+	query := fmt.Sprintf(`
+		DECLARE @from_lsn binary(10), @to_lsn binary(10), @last_lsn binary(10);
+		SET @last_lsn = %s;
+		SET @from_lsn = sys.fn_cdc_increment_lsn(@last_lsn);
+		SET @to_lsn = sys.fn_cdc_get_max_lsn();
+		SELECT * from cdc.fn_cdc_get_all_changes_%s_%s ( @from_lsn, @to_lsn, 'all' );
+`, lastLsn, schema, q.TableDef.TableName)
+	//println(query)
```
Comment (gra-moore) [inline internal/db/query.go:121]: remove

File: internal/layers/layer.go [hunk 3]
```diff
@@ -440,6 +458,23 @@ func getSince(db *sql.DB, tableDef *conf.TableMapping) (string, error) {
 			return "", err
 		}
 		s = fmt.Sprintf("%s", dt.Format("2006-01-02T15:04:05.000Z"))
+	} else if tableDef.CDCEnabled {
+		//schema := "dbo"
```
Comment (gra-moore) [inline internal/layers/layer.go:462]: remove commented code

**Review by gra-moore — CHANGES_REQUESTED** [review]

**Review by gra-moore — APPROVED** [review]
